language: php

dist: trusty

matrix:
  include:
    - php: 7.2
      env: DB=MYSQL

before_script:
  # Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  # Install composer dependencies
  - composer validate
  - composer require --prefer-dist --prefer-stable --no-update --no-suggest silverstripe/recipe-cms:^4
  - composer require --prefer-dist --prefer-stable --no-update --no-suggest phpunit/phpunit:^5.7
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
 - vendor/bin/phpunit
