mappings:
  KnockoutNumericField: AntonyThorpe\Knockout\KnockoutNumericField
  KnockoutConfirmedPasswordField: AntonyThorpe\Knockout\KnockoutConfirmedPasswordField
  KnockoutPasswordField: AntonyThorpe\Knockout\KnockoutPasswordField
  KnockoutOptionsetField: AntonyThorpe\Knockout\KnockoutOptionsetField
  KnockoutEmailField: AntonyThorpe\Knockout\KnockoutEmailField
  KnockoutConfirmedPasswordField: AntonyThorpe\Knockout\KnockoutConfirmedPasswordField
  KnockoutFormAction: AntonyThorpe\Knockout\KnockoutFormAction
  KnockoutTextareaField: AntonyThorpe\Knockout\KnockoutTextareaField
  KnockoutTextField: AntonyThorpe\Knockout\KnockoutTextField
  KnockoutDropdownField: AntonyThorpe\Knockout\KnockoutDropdownField
  KnockoutForm: AntonyThorpe\Knockout\KnockoutForm
