name: CI

# Controls when the workflow will run
on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci:
    permissions:
      pull-requests: read
      contents: read
      actions: write
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      composer_require_extra:
        phpunit/phpunit:^11.3
        php-http/discovery:^1.20
        silverstripe/installer:^6.2.0
